### ISSUE TITLE
Exits on windows after a few seconds

### ISSUE THREAD

**Issue by JakeGinnivan** [Qard/onchange#10]
`"watch-tests": "onchange 'test/thing.tests.js' -- node test/thing.tests.js",` exits after a few seconds.

If I remove the single quotes it works fine

`"watch-tests": "onchange test/thing.tests.js -- node test/thing.tests.js",`

**Comment by Qard** [comment]
I don't do anything with the quotes, so it probably has something to do with how Windows handles quotes in child_process.spawn. I've merged that cross-spawn PR, is this fixed by that? I don't have a Windows machine set up to test on.

**Comment by JakeGinnivan** [comment]
The cross-spawn PR didn't fix this. I just updated and still have the same issue

**Comment by bitinn** [comment]
If you are using windows command prompt, you might be running into this, basically, single quote isn't the same on windows.

- http://superuser.com/questions/324278/how-to-make-windows-command-prompt-treat-single-quote-as-though-it-is-a-double-q
- http://stackoverflow.com/questions/24173825/what-does-single-quote-do-in-windows-batch-files
